### ISSUE TITLE
Error executing lua .../.vim/plugged/nvim-cmp/lua/cmp/config/default.lua:23: snippet engine is not configured.

### ISSUE THREAD

**Issue by acicco** [hrsh7th/nvim-cmp#102]
Hi there,

I'm transitioning from nvim-compe, I managed to get it almost running with the same settings as with compe, however when I try to complete a lsp snippet it throws with the title error.

Can I get some help please? it gets replaced with a 0 when I hit enter
![image](https://user-images.githubusercontent.com/12491883/131146441-14903410-9832-4695-a47c-0473e1092f8f.png)

![image](https://user-images.githubusercontent.com/12491883/131146479-e170b5a9-da6f-4494-af25-589c8353aec3.png)

**Comment by JoseConseco** [comment]
I had simmilar error - it was caused by bad mapping config (it is better to create new config from  cmp readme, rather than trying to convert old compe mappings config imo -  or else u end up with above bug). Here is config that worked witout error (I use tab, to cycle through entries, or just to snippet tabstops;  ctrl+space accepts selected item, or expands snippet ) :+1: 

```lua
mapping = {
		['<C-p>'] = cmp.mapping.select_prev_item(),
		['<C-n>'] = cmp.mapping.select_next_item(),
		['<S-Tab>'] = function(fallback)
				if vim.fn['vsnip#jumpable']() == 1 then
					vim.fn.feedkeys(t('<plug>(vsnip-jump-prev)'), '')
				elseif vim.fn.pumvisible() == 1 then
					vim.fn.feedkeys(t('<C-p>'), '')
				else
					fallback()
				end
		end,
		['<Tab>'] = function(fallback)
				if vim.fn['vsnip#jumpable']() == 1 then
					vim.fn.feedkeys(t('<plug>(vsnip-jump-next)'), '')
				elseif vim.fn.pumvisible() == 1 then
					vim.fn.feedkeys(t('<C-n>'), '')
				else
					fallback()
				end
		end,
		['<C-d>'] = cmp.mapping.scroll_docs(-4),
		['<C-f>'] = cmp.mapping.scroll_docs(4),
		-- ['<C-Space>'] = cmp.mapping.complete(),
		['<C-e>'] = cmp.mapping.close(),
		['<CR>'] = cmp.mapping.confirm({
			behavior = cmp.ConfirmBehavior.Insert,
			select = true,
		}),
		['<C-Space>'] = function(fallback)
			if vim.fn['vsnip#available']() == 1 then
				vim.fn.feedkeys(t('<Plug>(vsnip-expand-or-jump)'), '')
			elseif vim.fn.pumvisible() == 1 then
				vim.fn.feedkeys(t('<CR>'), '')
			else
				fallback()
			end
		end,
	}
```

**Comment by Iron-E** [comment]
I am getting the same thing. I think it is related to attempting to use the builtin snippet support, rather than installing a snippet engine. With `nvim-compe` the following LSP configuration allowed for snippet support, without installing `vsnip`, `LuaSnip`, etc.:

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport =
{
	properties =
	{
		'documentation',
		'detail',
		'additionalTextEdits',
	}
}

lspconfig['<server>'].setup {capabilities = capabilities}
```

However, trying this gives the following in `cmp`:

```log
E5108: Error executing lua ...te/pack/packer/start/nvim-cmp/lua/cmp/config/default.lua:23: snippet engine is not configured.
```

**Comment by acicco** [comment]
> @acicco Do you dislike snippet engine? I think it will be solved if you install snippet engine.
> What should I do with the `get ~` item if I don't set up the snippet engine?

@hrsh7th 

I do have a snippet engine installed, I have vsnips, I followed the instructions and added it to the sources, is there anything else I should do?

**Comment by babygau** [comment]
Have you tried this?
https://github.com/hrsh7th/cmp-nvim-lsp

**Comment by Iron-E** [comment]
I'm personally using that, don't know about OP

**Comment by bragjo** [comment]
I'm having the same issue

**Comment by avatsavirs** [comment]
I'm getting the same error. 
I tried installing `vim-vsnip` and `cmp-vsnip` as dependencies(using packer.nvim) for `nvim-cmp` and added `cmp-vsnip` in my sources but it didn't work for me. 
Also is there a way to opt out of using the snippet engine completely? I don't want to cmp to complete the signatures for the selected function as I'm often passing a function as an argument. I liked how compe just selected the function name. It would be really nice if using signatures was an optional feature. 
Let me know if I can do anything to help in solving this issue. 
Thanks. 

PS: This is my config for reference: 
/lua/plugins/init.lua
```lua
vim.cmd([[ packadd packer.nvim ]]);

return require('packer').startup({
  function(use)
    use({
      "hrsh7th/nvim-cmp",
      config = [[ require('plugins.nvim-cmp') ]],
      requires = {
        "hrsh7th/cmp-nvim-lsp",
        "hrsh7th/cmp-buffer",
        "hrsh7th/cmp-path",
        "hrsh7th/vim-vsnip",
        "hrsh7th/cmp-vsnip",
      }
    });
  end
});
```
/lua/plugins/nvim-cmp.lua
```lua
local cmp = require('cmp');
local types = require('cmp.types');

local check_back_space = function()
  local col = vim.fn.col('.') - 1;
  if col == 0 or vim.fn.getline('.'):sub(col, col):match '%s' then
    return true
  else
    return false
  end
end

local custom_select_next = function()
  if vim.fn.pumvisible() == 1 then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<C-n>', true, true, true), 'n');
  elseif check_back_space() then
    vim.fn.feedkeys(vim.api.nvim_replace_termcodes('<Tab>', true, true, true), 'n');
  else
    local cmp_complete = cmp.mapping.complete();
    cmp_complete();
  end
end

cmp.setup({
  preselect = types.cmp.PreselectMode.Item,
  mapping = {
    ['<S-Tab>'] = cmp.mapping.select_prev_item(),
    ['<Tab>'] = custom_select_next,
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    })
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'buffer' },
    { name = 'path' },
    { name = 'vsnip' }
  },
});
```

**Comment by hrsh7th** [comment]
I understoo dIt's documentation bug. Please wait.

**Comment by babygau** [comment]
hmm, I haven't got this issue, here is my config, sorry, it's written in `fennel` but hope it give you some clues
```fennel
;; nvim-cmp.fnl
(def- cmp-srcs
  [{:name :nvim_lsp}
   {:name :conjure}
   {:name :luasnip}
   {:name :buffer}
   {:name :path}
   {:name :nvim_lua}
   {:name :calc}
   {:name :emoji}])

(defn- check-back-space []
  (let [col (- (vim.fn.col ".") 1)]
    (if (or (= col 0) (: (: (vim.fn.getline ".") :sub col col) :match "%s"))
        true false)))

(cmp.setup
  {:formatting
   {:format (fn [entry item]
              (set item.kind
                   (.. (or (get cmp-kinds item.kind) "")
                       " " item.kind))
              (set item.menu (or (get cmp-src-menu-items entry.source.name) ""))
              item)}
   :mapping
   {:<C-p> (cmp.mapping.select_prev_item)
    :<C-n> (cmp.mapping.select_next_item)
    :<Up> (cmp.mapping.scroll_docs -4)
    :<Down> (cmp.mapping.scroll_docs 4)
    :<C-s> (cmp.mapping.complete)
    :<C-e> (cmp.mapping.close)
    ;; :<CR> (cmp.mapping.confirm
    ;;         {:behavior cmp.ConfirmBehavior.Insert
    ;;          :select true})
    :<Tab> (cmp.mapping (fn [fallback]
              (if (= (vim.fn.pumvisible) 1) (vim.fn.feedkeys (t :<C-n>) "n")
                (and luasnip (luasnip.expand_or_jumpable)) (vim.fn.feedkeys (t :<Plug>luasnip-expand-or-jump) "")
                (check-back-space) (vim.fn.feedkeys (t :<Tab>) "n")
                (fallback))) ["i" "s"])
    :<S-Tab> (cmp.mapping (fn [fallback]
                (if (= (vim.fn.pumvisible) 1)
                  (vim.fn.feedkeys (t :<C-p>) "n")
                  (and luasnip (luasnip.jumpable (- 1))) 
                   (vim.fn.feedkeys (t :<Plug>luasnip-jump-prev) "")
                   (vim.fn.feedkeys (t :<S-Tab>) "n")
                  (fallback))) ["i" "s"])}
   :snippet
   {:expand (fn [args]
              (luasnip.lsp_expand args.body))}
   :sources cmp-srcs})
;; Load friendly-snippets
(snippet.lazy_load)
```

and this is `lspconfig` setup

```fennel
;; lsp.fnl
(local cmp/lsp (require :cmp_nvim_lsp))

(def- capabilities
  (let [c (vim.lsp.protocol.make_client_capabilities)]
    ;; Delegate snippet support to any completion engine such as `nvim-cmp`
    (set c.textDocument.completion.completionItem.snippetSupport true)
    (set c.textDocument.completion.completionItem.resolveSupport {:properties [:documentation
                                                                               :detail
                                                                               :additionalTextEdits]})
    (set c.textDocument.completion.completionItem.preselectSupport true)
    (set c.textDocument.completion.completionItem.insertReplaceSupport true)
    (set c.textDocument.completion.completionItem.deprecatedSupport true)
    (set c.textDocument.completion.completionItem.commitCharactersSupport true)
    (set c.textDocument.completion.completionItem.tagSupport {:valueSet [1]})
    ;; Code action
    ;; (set c.textDocument.codeAction
    ;;      {:dynamicRegistration true
    ;;       :codeActionLiteralSupport {:codeActionKind {:valueSet ((fn []
    ;;                                                                (def- res
    ;;                                                                  (vim.tbl_values vim.lsp.protocol.CodeActionKind))
    ;;                                                                (table.sort res)
    ;;                                                                res))}}})
    (cmp/lsp.update_capabilities c)))

;; .....
;; .....
(each [server config (pairs servers)]
  (let [lsp/server (. lspconfig server)]
        (-> {:on_attach enhanced-attach
             ;; This will merge our defined capabilities to each lspserver in the list
             : capabilities  
             :flags {:debounce_text_changes 150}}
            (merge config)
            (lsp/server.setup))))
```
Pls note that I trimmed down some unwanted codes.

**Comment by hrsh7th** [comment]
@babygau Thank you. Because you've set nvim-cmp up correctly.

@acicco @avatsavirs @Iron-E 
I've updated the README.md See https://github.com/hrsh7th/nvim-cmp#basic-configuration

We must set `snippet.expand` up.

And I've added minimal vimrc (it works with nvim-lspconfig). https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim

**Comment by Iron-E** [comment]
Is there a `snippet.expand` function that doesn't require a dedicated snippet plugin? `compe` had LSP snippet expansion builtin and I'm trying to replicate that.

Thank you!

**Comment by hrsh7th** [comment]
I think your solution has a cursor position problem... but good to hear.

**Comment by acicco** [comment]
Thanks a lot @hrsh7th , with your basic configuration I get what I had on compe, I prefer how vsnip completes my snippets rather than luasnips

**Comment by bragjo** [comment]
@hrsh7th I'm still getting the same error even after reading the updated readme.

This is my cmp.lua config file:

`local present, cmp = pcall(require, "cmp")
if not present then
    return
end

cmp.setup({
    confirmation = { default_behaviour = cmp.ConfirmBehavior.Replace },
    sources = {
        { name = "buffer" },
        { name = "nvim_lsp" },
        { name = "nvim_lua" },
        { name = "path" },
        { name = "vsnip" }
        -- { name = "luasnip" }
    },
    mapping = {
        ["<cr>"] = cmp.mapping.confirm(),
        ["<s-tab>"] = cmp.mapping.select_prev_item(),
        ["<tab>"] = cmp.mapping.select_next_item(),
    },
    formatting = {
        format = function(entry, vim_item)
            vim_item.menu = ({
                buffer = "[Buffer]",
                nvim_lsp = "[LSP]",
                luasnip = "[LuaSnip]",
                nvim_lua = "[Lua]",
                latex_symbols = "[Latex]",
            })[entry.source.name]
            vim_item.kind = ({
                Text          = ' Text',
                Method        = ' Method',
                Function      = ' Function',
                Constructor   = ' Constructor',
                Field         = ' Field',
                Variable      = ' Variable',
                Class         = ' Class',
                Interface     = 'ﰮ Interface',
                Module        = ' Module',
                Property      = ' Property',
                Unit          = ' Unit',
                Value         = ' Value',
                Enum          = ' Enum',
                Keyword       = ' Keyword',
                Snippet       = '﬌ Snippet',
                Color         = ' Color',
                File          = ' File',
                Reference     = ' Reference',
                Folder        = ' Folder',
                EnumMember    = ' EnumMember',
                Constant      = ' Constant',
                Struct        = ' Struct',
                Event         = ' Event',
                Operator      = 'ﬦ Operator',
                TypeParameter = ' TypeParameter',
            })[vim_item.kind]
            return vim_item
        end,
        snippet = {
            expand = function(args)
                vim.fn["vsnip#anonymous"](args.body)
            end
        },
    },
})
`

**Comment by hrsh7th** [comment]
@bragjo I don't found the cause in  your part of config. Could you provide your full config?

**Comment by acicco** [comment]
@bragjo  Could it be that you're missing 
`    Plug 'hrsh7th/cmp-vsnip'` in your requires map?

**Comment by bragjo** [comment]
> @bragjo I don't found the cause in your part of config. Could you provide your full config?

Here is my complete plugins.lua:

```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.cmd 'packadd packer.nvim'
end

return require('packer').startup(function()

    -- Packer can manage itself
    use 'wbthomason/packer.nvim'

    -- Lsp config and cmp-nvim-lsp
    use {
        'neovim/nvim-lspconfig',
        config = function() require("config.lspconfig") end
    }

    -- Lspinstall for easier installation of LSPs via :LspInstall
    use {
        'kabouzeid/nvim-lspinstall',

        -- LspInstall config
        config = function() require("config.lspinstall") end
    }

        -- Completion engine
    use { 
        'hrsh7th/nvim-cmp',
        requires = {
            'hrsh7th/cmp-buffer',
            'hrsh7th/cmp-nvim-lsp',
            'hrsh7th/vim-vsnip',
            'hrsh7th/cmp-vsnip',
            'hrsh7th/cmp-buffer',
        },
        -- Cmp config
        config = function() require("config.cmp") end
    }

     -- Snippets collection for all kinds of different programming languages
    use {
        "rafamadriz/friendly-snippets"
    }

    -- Galaxyline base
    use {
        'glepnir/galaxyline.nvim',
        branch = 'main',

        -- Galaxyline config
        config = function() require("config.galaxyline") end,

        -- Some optional icons
        requires = {'kyazdani42/nvim-web-devicons', opt = true}
    }

    -- Show colors instead of just hexcode in e.g. css via colorizer
    use {
        'norcalli/nvim-colorizer.lua',

        -- Colorizer config
        config = function() require("config.colorizer") end
    }

    -- Colorpicker, NOTE! Zenity needs to be installed
    use {
        'KabbAmine/vCoolor.vim'
    }

    -- Telescope fuzzy finder
    use {
        'nvim-telescope/telescope.nvim',
        requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}},

        -- Telescope config
        config = function() require("config.telescope") end
    }


    -- Bufferline
    use {
        'akinsho/bufferline.nvim', 
        requires = 'kyazdani42/nvim-web-devicons'
    }

    -- Colorscheme tokyonight
    use {
        'ghifarit53/tokyonight-vim'
    }

    -- Better syntax highlightning via treesitter
    use {
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate',

        -- Treesitter config
        config = function() require("config.treesitter") end
    }

    -- Easy commenting/uncommenting using nvim-comment

    use {
        use "terrortylor/nvim-comment",
        require('nvim_comment').setup()

    }

    -- Live preview
    use {
        'turbio/bracey.vim',
        run = "'do': 'npm install --prefix server'"
    }


end)
```

and this is the full config / cmp.lua file:

```lua
local present, cmp = pcall(require, "cmp")
if not present then
    return
end

cmp.setup({
    confirmation = { default_behaviour = cmp.ConfirmBehavior.Replace },
    sources = {
        { name = "buffer" },
        { name = "nvim_lsp" },
        { name = "nvim_lua" },
        { name = "path" },
        { name = "vsnip" }
    },
    mapping = {
        ["<cr>"] = cmp.mapping.confirm(),
        ["<s-tab>"] = cmp.mapping.select_prev_item(),
        ["<tab>"] = cmp.mapping.select_next_item(),
    },
    formatting = {
        format = function(entry, vim_item)
            vim_item.menu = ({
                buffer = "[Buffer]",
                nvim_lsp = "[LSP]",
                vsnip = "[vsnip]",
                nvim_lua = "[Lua]",
                latex_symbols = "[Latex]",
            })[entry.source.name]
            vim_item.kind = ({
                Text          = ' Text',
                Method        = ' Method',
                Function      = ' Function',
                Constructor   = ' Constructor',
                Field         = ' Field',
                Variable      = ' Variable',
                Class         = ' Class',
                Interface     = 'ﰮ Interface',
                Module        = ' Module',
                Property      = ' Property',
                Unit          = ' Unit',
                Value         = ' Value',
                Enum          = ' Enum',
                Keyword       = ' Keyword',
                Snippet       = '﬌ Snippet',
                Color         = ' Color',
                File          = ' File',
                Reference     = ' Reference',
                Folder        = ' Folder',
                EnumMember    = ' EnumMember',
                Constant      = ' Constant',
                Struct        = ' Struct',
                Event         = ' Event',
                Operator      = 'ﬦ Operator',
                TypeParameter = ' TypeParameter',
            })[vim_item.kind]
            return vim_item
        end,
        snippet = {
            expand = function(args)
                vim.fn["vsnip#anonymous"](args.body)
            end
        },
    },
})
```
@acicco I have tried that aswell, see above

**Comment by babygau** [comment]
I think you could try remove packer compiled file and run PackerSync again

**Comment by bragjo** [comment]
I got this fixed by installing friendly-snippets, but it should work with just LSP too, removed packer compiled file and ran PackerSync without results.

**Comment by ibhagwan** [comment]
Just FYI, if anyone finds this thread and would like to use `nvim-cmp` without a snippet engine, I use the below, I found @Iron-E's `snippet.expand` but I was having issues with it, cursor was going to start of the replaced text and it would replace the entire line instead of just the completed text, the below works great for me:

```lua
  snippet = {
    expand = function(args)
      vim.cmd("norm! ciw " .. args.body)
      vim.api.nvim_feedkeys(
        vim.api.nvim_replace_termcodes("<Right><Space>",
          true, false, true), 'i', true)
    end,
  },

```

**Comment by Iron-E** [comment]
That's better. Thanks!

**Comment by Iron-E** [comment]
Hey, thanks for letting me know! I'll see if I can get it to work with another `string.match` later today
