### ISSUE TITLE
nvim-cmp not working at all

### ISSUE THREAD

**Issue by Wmbat** [hrsh7th/nvim-cmp#110]
Hello,

I've been trying to setup `nvim-cmp` all day now but I can't get it to work, 

I first tried to do everything listed in the readme but it didn't work.
I then tried to follow [this](https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion) tutorial from `nvim-lspconfig` but that also did not work.

I get no errors whatsoever, I have nvim-cmp & cmp-buffer installed through packer. But since I have no error messages, I have no idea on where to even begin at fixing it. 

This is the [repo](https://github.com/Wmbat/nvim-config) where all my config files are if you want to take a look. all lsp related config is in the [lua/dev/lsp.lua](https://github.com/Wmbat/nvim-config/blob/main/lua/dev/lsp.lua) file.

Thank you for your time

**Comment by rockerBOO** [comment]
I think this requires further debugging. Glancing at your config you are using onmifunc which might conflict (but lsp completions should be working with it). You can make sure its running setup by using something like `print('running cmp setup')`.

**Comment by Wmbat** [comment]
The file is definitely loading, I have all the `nvim-lspconfig` diagnostics working. It's just that the completion never pops up or shows no sign of life. So when I had a print statement in the lsp.lua file, all seem file, printing the local `cmp` variable also seem to return a valid address. After that, I have no idea what to do

**Comment by Shougo** [comment]
I think you should create the minimal vimrc to reproduce the problem.

**Comment by Wmbat** [comment]
I've made a minimal repro [here](https://github.com/Wmbat/nvim-config/tree/minimal_repro) which only has 3 plugins installed, `nvim-lspconfig`, `nvim-cmp` and `cmp-buffer`. The completion still does not appear. So my problem is either in my lsp setup, or something else, i'm not too sure. I have a correct neovim verison (v0.5.0-dev+1375-gca802046b). So i'm a bit lost.

**Comment by Shougo** [comment]
Well...  You should create one minimal vimrc without packer.
OK.  I will create the minimal.

**Comment by Shougo** [comment]
Wow.  My minimal vimrc does not work...

```vim
if &compatible
  set nocompatible
endif

set runtimepath+=~/src/nvim-cmp
set runtimepath+=~/src/cmp-buffer

lua <<EOF
  local cmp = require'cmp'.setup()

  cmp.setup {
    -- You can set mappings if you want
    mapping = {
      ['<C-p>'] = cmp.mapping.select_prev_item(),
      ['<C-n>'] = cmp.mapping.select_next_item(),
      ['<C-d>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.close(),
      ['<CR>'] = cmp.mapping.confirm({
        behavior = cmp.ConfirmBehavior.Insert,
        select = true,
      })
    },

    -- You should specify your *installed* sources.
    sources = {
      { name = 'buffer' },
    },
  }
EOF
```

@hrsh7th Can you provide the minimal vimrc for me?

**Comment by hrsh7th** [comment]
I've added the minimal vimrc. https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim
@Wmbat This minimal vimrc allows you to complete `neovim/lspconfig`. Please looking into it.

**Comment by Wmbat** [comment]
Ok, I setup neovim with the minimal vimrc you linked. but the completion still doesn't work. The LSP does work though. I tried both CCLS & Clangd and both LSP provided me with errors (on code with syntax errors). 

It has to be a problem on my side, as it works for everyone else, but I have no idea what it is

**Comment by hrsh7th** [comment]
@Wmbat I think your config didn't install cmp-nvim-lsp.
https://github.com/Wmbat/nvim-config/blob/main/lua/plugins.lua#L47

**Comment by Wmbat** [comment]
My config did not, but I copied your minimal vimrc and it also didn't work there. @hrsh7th

**Comment by hrsh7th** [comment]
Hm... I'm getting it to work with the following configuration now...

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn['vsnip#anonymous'](args.body)
    end
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.clangd.setup {
  capabilities = capabilities,
}
EOF
```

**Comment by Wmbat** [comment]
Yeah, I have the exact same code right now and it does not work. Which is why i'm really confused about what is not working

**Comment by Wmbat** [comment]
OOHHH, I think i have it fixed, It seems like the completion does not working with neovim v0.5.0-dev+1375-gca802046b. I've fully removed it and installed neovim v0.5.0 and it works. That's a really weird bug.

It also worked with neovim v0.6.0-dev+198-g81f4de08b. I think the version I had predates the 0.5 release

**Comment by hrsh7th** [comment]
For LSP debugging, You can set `vim.lsp.set_log_level("debug")` and then `~/.cache/nvim/lsp.log` will be wrote all LSP payloads.

**Comment by hrsh7th** [comment]
Hm....! I have not idea for it. 😭

**Comment by Wmbat** [comment]
Yeah, it's a bit weird. I'm not sure why it didn't work for that version

**Comment by horseinthesky** [comment]
Setup lazy loading packer. Working perfectly fine. Please welcome to use it as a POC
https://gist.github.com/horseinthesky/26d813d2974b27b5d142bb8a412d2ba3
