### ISSUE TITLE
Function signature not expanding on confirmation for some LSPs

### ISSUE THREAD

**Issue by ghillb** [hrsh7th/nvim-cmp#488]
**Describe the bug**
Hi, when confirming a completion the function signature does not expand (screenshots), this is happening with pyright and sumneko_lua for example. 

actual behavior in a `.py` file: 

type "pri" ->confirm -> get only "print"

Suggestion, before confirmation:
![before](https://user-images.githubusercontent.com/35503959/140643318-e420052b-40d5-43fc-a8f6-3acf14a83c9d.png)

After confirmation:
![image](https://user-images.githubusercontent.com/35503959/140643333-32aa425b-445f-4d22-823b-f613e8dfabaf.png)

Am I doing something wrong or is this just how it is supposed to be?

**Minimal config based on [this](https://github.com/hrsh7th/nvim-cmp/blob/main/utils/vimrc.vim)**

```vim
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = {
    { name = "nvim_lsp" },
    { name = "buffer" },
  },
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

require'lspconfig'.pyright.setup {
  capabilities = capabilities,
}
EOF

```

**To Reproduce**
1. Install pyright (`npm i -g pyright`)
2. Open a python file 
3. Try completing functions 

**Expected behavior**
Function signature is expanded
type "pri" ->confirm -> get "print(args & cursor)"

**Additional context**
It works just fine in rust files with rust analyzer.

Before:
![image](https://user-images.githubusercontent.com/35503959/140643459-4a9d9627-ddcf-433f-9eae-280e77253af7.png)

After:
![Screenshot 2021-11-07 124311](https://user-images.githubusercontent.com/35503959/140643487-182e7535-2032-4c77-9d5b-5fd95c1d87ba.png)

**Comment by pedro757** [comment]
You should use a `pair-wise` plugin like `nvim-autopairs` or `vim-endwise`

I use `windwp/nvim-autopairs` and I have configured it as the [plugin docs](https://github.com/windwp/nvim-autopairs#you-need-to-add-mapping-cr-on-nvim-cmp-setupcheck-readmemd-on-nvim-cmp-repo) specify

**Comment by hrsh7th** [comment]
@ghillb This plugin doesn't support displaying the function signature.

If you hope to show function signature, you should install https://github.com/ray-x/lsp_signature.nvim

**Comment by hrsh7th** [comment]
@David-Else Yes. You can use it to display signature help. However, it is not a general solution. It would be convenient if you were satisfied with this appearance.
_google translated_

**Comment by David-Else** [comment]
@hrsh7th Awesome! How do I use it? If I enter a function signature I get no information:

![Screenshot from 2021-12-01 13-23-10](https://user-images.githubusercontent.com/12832280/144242649-6229f201-602b-4011-a10e-faf0550d89b3.png)


If I start to type I get things I don't want:

![Screenshot from 2021-12-01 13-23-24](https://user-images.githubusercontent.com/12832280/144242417-856ff70d-d4d6-4561-b1d2-d1d44c054421.png)
```
  call plug#begin('~/.config/nvim/plugged')
     Plug 'hrsh7th/nvim-cmp'    
     Plug 'hrsh7th/cmp-nvim-lsp'
     Plug 'hrsh7th/cmp-nvim-lsp-signature-help'
     Plug 'hrsh7th/cmp-path'
     Plug 'hrsh7th/cmp-buffer'                                                                                                                                              
  call plug#end()    

  sources = {
    { name = 'nvim_lsp' },
    { name = 'nvim_lsp_signature_help' },
    { name = 'path' },
    { name = 'buffer', keyword_length = 4 },
  },
```

**Comment by hrsh7th** [comment]
@David-Else I've fixed. it was a source's bug.

**Comment by David-Else** [comment]
@hrsh7th Thanks! This is fantastic, just what is needed!

 It now triggers, but is this a bug? At first it works and `x: number` is highlighted:
![Screenshot from 2021-12-01 13-50-34](https://user-images.githubusercontent.com/12832280/144246351-0604d8cb-40c5-437b-9ca1-f3d420539360.png)

but when I move to the 2nd number, then it still shows highlighted `x: number`

![Screenshot from 2021-12-01 13-50-50](https://user-images.githubusercontent.com/12832280/144246449-eec0b5b8-2f74-4d2a-a8ee-eb0a0df46588.png)

also, why `x: number Text` and not just `x: number`?

(I am using Deno LS)
```ts
function test(x: number, y: number) {
  return x;
}

test(23,
```

**Comment by hrsh7th** [comment]
Hm... It's may be cmp-nvim-lsp-signature-help's bug.
Current cmp-nvim-lsp-signature-help is rough sketch phase. I will improve it.

**Comment by hrsh7th** [comment]
I've improved the cmp-nvim-lsp-signature-help but I think we can't support the signature help perfectly.
So I've introduced the workaround for it.

**Comment by hrsh7th** [comment]
If the language server returns `activeParameter`. the cmp-nvim-lsp-signature-help works expected therefore if it isn't so, the source would show all parameters.
